name: 'Azure SQL Deploy'
description: 'Deploy a database project, DACPAC, or a SQL script to Azure SQL database'
inputs:
  server-name:
    description: 'Name of the Azure SQL Server name, like Fabrikam.database.windows.net.'
    required: false
  connection-string:
    description: 'The connection string, including authentication information, for the Azure SQL Server database.'
    required: true
  client-id:
    description: 'For Azure Active Directory connections, the application (client) ID from the registered Azure application'
    required: false
  tenant-id:
    description: 'For Active Directory connections, the tenant ID from the Azure Active Directory instance'
    required: false
  dacpac-package:
    description: 'Path to DACPAC file to deploy'
    required: false
  sql-file:
    description: 'Path to SQL script file to deploy'
    required: false
  project-file:
    description: 'Path to the SQL database project file to deploy'
    required: false
  arguments:
    description: 'In case DACPAC option is selected, additional SqlPackage arguments that will be applied.'
    required: false
  build-arguments:
    description: 'In case Build and Publish option is selected, additional arguments that will be applied to dotnet build when building the database project.'
    required: false
runs:
  using: 'node12'
  main: 'lib/main.js'
