name: 'Azure SQL Deploy'
description: 'Deploy a DACPAC or a SQL script to Azure SQL database'
inputs:
  server-name:
    description: 'Name of the Azure SQL Server name, like Fabrikam.database.windows.net.'
    required: true
  connection-string:
    description:  'The connection string, including authentication information, for the Azure SQL Server database.'
    required: true
  dacpac-package:
    description: 'Path to DACPAC file to deploy'
  sql-file:
    description: 'Path to SQL script file to deploy'
  project-file:
    description: 'Path to the SQL database project file to deploy'
  arguments:
    description: 'In case DACPAC option is selected, additional SqlPackage arguments that will be applied. When SQL query option is selected, additional sqlcmd arguments will be applied.'
runs:
  using: 'node12'
  main: 'lib/main.js'
