name: adhoc-tests

# Manually trigger this workflow, test auth/connection settings by setting the ADHOC_CONNECTION_STRING_NO_DATABASE GitHub secret.

on: workflow_dispatch

permissions:
  id-token: write # This is needed for Azure login with OIDC

jobs:
  deploy:
    environment: Automation test # this environment requires approval before running the action
    runs-on: ubuntu-latest
    permissions:
      checks: write
      id-token: write
    continue-on-error: true

    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Install sqlpackage
      run: dotnet tool install -g Microsoft.SqlPackage

    - name: Run sqlpackage
      run: sqlpackage /action:Export /scs:"${{ SECRETS.ADHOC_TEST_CONNECTION_STRING }}" /targetfile:"${{ runner.temp }}/ExportCustomerDatabase.bacpac" /df:"${{ runner.temp }}/ExportCustomerDatabase.log"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          ${{ runner.temp }}/ExportCustomerDatabase.bacpac
          ${{ runner.temp }}/ExportCustomerDatabase.log