# This workflow verifies lib/main.js has latest changes from src/*.ts
on: pull_request

jobs:
  build:
    name: 'Build main.js'
    runs-on: ubuntu-latest
    steps:
    - name: 'Check out'
      uses: actions/checkout@v3

    - name: 'Setup git config'
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: 'Checkout out current branch'
      run: |
        git fetch
        git checkout ${GITHUB_HEAD_REF}

    - name: 'Validate build'
      run: |
        npm install
        npm run build

    - name: 'Check if main.js has differences'
      run: |
        git status
        echo "GIT_DIFF=$(git diff --name-only ./lib)" >> $GITHUB_ENV

    - name: 'Commit main.js changes'
      if: ${{ contains(env.GIT_DIFF, 'lib/') }}
      run: |
        git commit -m "main.js changes for ${GITHUB_SHA}" ./lib
        git push