# This workflow verifies lib/main.js has latest changes from src/*.ts
on: pull_request

jobs:
  check-lib:
    name: Build main.js and diff on
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
    - name: Check out
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Validate build
      run: |
        npm ci
        npm run build

    - name: Check if main.js has differences
      if: matrix.os != 'windows-latest'
      run: echo "diff=$(git diff --ignore-space-at-eol --text lib/main.js | wc -l)" >> $GITHUB_ENV
      
    - name: Check if main.js has differences
      if: matrix.os == 'windows-latest'
      run: echo "diff=$(git diff --ignore-space-at-eol --text lib/main.js | wc -l)" >> $env:GITHUB_ENV

    # If main.js was different than expected, upload the actual version
    - name: Upload actual main.js
      if: ${{ env.diff > 0}}
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: main.js-${{ matrix.os }}
        path: lib/main.js

  final-check:
    name: Check if main.js has differences on both Ubuntu and Windows
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: check-lib
    steps:
    - name: Download artifact
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
    
    - name: Check if both artifacts exist
      run: |
        ls -R
        if [ -d "main.js-windows-latest" ] && [ -d "main.js-ubuntu-latest" ]; then
          echo "main.js difference detected. Please check the artifacts for more details."
          exit 1
        fi