# In TypeScript actions, `lib/` is a special directory. When you reference
# an action with the `uses:` property, `lib/index.js` is the code that will be
# run. For this project, the `lib/index.js` file is transpiled from other
# source files. This workflow ensures the `lib/` directory contains the
# expected transpiled code.
#
# If this workflow is run from a feature branch, it will act as an additional CI
# check and fail if the checked-in `lib/` directory does not match what is
# expected from the build.
on: pull_request

jobs:
  check-lib:
    name: Check index.js
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Validate build
      run: |
        npm install
        npm run build

    # This will fail the workflow if the `lib/` directory is different than
    # expected.
    - name: Compare Directories
      id: diff
      run: |
        if [ ! -d lib/ ]; then
          echo "Expected lib/ directory does not exist.  See status below:"
          ls -la ./
          exit 1
        fi
        if [ "$(git diff --ignore-space-at-eol --text lib/ | wc -l)" -gt "0" ]; then
          echo "Detected uncommitted changes after build. See status below:"
          git diff --ignore-space-at-eol --text lib/
          exit 1
        fi

    # If `lib/` was different than expected, upload the expected version as a
    # workflow artifact.
    - if: ${{ failure() && steps.diff.outcome == 'failure' }}
      name: Upload Artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: lib
        path: lib/