# This workflow verifies lib/main.js has latest changes from src/*.ts
on: pull_request

jobs:
  check-lib:
    name: Check main.js
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Validate build
      run: |
        npm install
        npm run build

    - name: Check if main.js has differences
      id: diff
      run: |
        if [ ! -d lib/ ]; then
          echo "Expected lib/ directory does not exist.  See status below:"
          ls -la ./
          exit 1
        fi
        if [ "$(git diff --ignore-space-at-eol --text lib/ | wc -l)" -gt "0" ]; then
          echo "Detected uncommitted changes after build. See status below:"
          git diff --ignore-space-at-eol --text lib/
          exit 1
        fi

    # If main.js was different than expected, upload the actual version
    - name: Upload actual main.js
      if: ${{ failure() && steps.diff.conclusion == 'failure' }}
      uses: actions/upload-artifact@v3
      with:
        name: main.js
        path: lib/main.js