# This workflow verifies lib/main.js has latest changes from src/*.ts
on: pull_request

jobs:
  check-lib:
    name: Check main.js
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Copy the committed main.js file
      run: mv lib/main.js /tmp

    - name: Validate build
      run: |
        npm install
        npm run build

    - name: Check if main.js has differences
      run: git diff --ignore-all-space --exit-code lib/main.js /tmp/main.js
      id: diff

    # If main.js was different than expected, upload the actual version
    - name: Upload actual main.js
      if: ${{ failure() && steps.diff.conclusion == 'failure' }}
      uses: actions/upload-artifact@v3
      with:
        name: main.js
        path: lib/main.js