name: ci-test

on:
  push:
    branches:
      - master
      - dev
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    types: [labeled]
      
jobs:

    deploy:
      if: ${{ github.event.label.name == 'test-wf' }}
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      - uses: actions/checkout@v2
#       if: steps.job-type.outputs.type == 'cron'
        name: Checkout from PR branch

      - name: Building latest changes
        run: |
          npm install --prod

      - uses: ./
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          sql-file: testsql.sql
