on: push

jobs:
  build_test_job:
    name: 'Build and test job'
    runs-on: ${{ matrix.os }}
    permissions: read-all
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest]
    steps:

    - name: 'Checking out repo code'
      uses: actions/checkout@v3

    - name: 'Validate build'
      run: |
        npm install
        npm run build
    - name: 'Run L0 tests'
      run: |
        npm run test