name: pr-check

on:
  pull_request:
#     branches:
#       - master
#       - 'releases/*'

jobs:
    deploy:
      environment: Automation test
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [windows-latest, ubuntu-latest]
      env:
        TEST_DB: 'SqlActionTest-${{ matrix.os }}'
        
      steps:
      - name: Checkout from PR branch
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Installing node_modules
        run: npm install

      - name: Build GitHub Action
        run: npm run build

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy a DACPAC with only a table to server
      - name: Test DACPAC Action
        uses: ./
        with:
          connection-string: '${{ secrets.AZURE_SQL_CONNECTION_STRING_NO_DATABASE }}Initial Catalog=${{ env.TEST_DB }};'
          dacpac-package: ./__testdata__/sql-action.dacpac

      # Execute testsql.sql via SQLCMD on server
      - name: Test SQL Action
        uses: ./
        with:
          connection-string: '${{ secrets.AZURE_SQL_CONNECTION_STRING_NO_DATABASE }}Initial Catalog=${{ env.TEST_DB }};'
          sql-file: ./__testdata__/testsql.sql
          arguments: '-v DbName="${{ env.TEST_DB }}"'
