# .github/workflows/sql-deploy.yml
on: [push]



jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/sql-action@v1
      with:
        server-name: mysqlserver-ramullig.database.windows.net
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        sql-file: 'sql/test1.sql'
